name: test-environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pymt
  - seaborn
  - matplotlib
  - pandas
  - numpy
  - pymt_cem
  - pymt_child
  - pymt_ecsimplesnow
  - pymt_gipl
  - pymt_hydrotrend
  - pymt_permamodel
  - pymt_sedflux
