{% set data = load_setup_py_data() %}


package:
  name: pymt
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  build:
    - python
    - pip

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - xarray
    - shapely
    - netcdf4
    - pyyaml
    - esmpy
    - cfunits
    - jinja2
    - model_metadata
    - scripting
    - landlab

test:
  requires:
    - pytest
  imports:
    - pymt
  commands:
    - pytest --pyargs pymt --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

about:
  home: http://github.com/csdms/pymt
  license: MIT
  license_file: LICENSE
  summary: The CSDMS Python Modeling Tools

  description: |
    pymt is the Python interface to the CSDMS modeling tools. It provides
    utilities that run, and couple models that expose the Basic
    Model Interface.
  doc_url: http://pymt.readthedocs.org
  dev_url: http://github.com/csdms/pymt
