name: Documentation

on:
    push:
        paths:
            - "docs/**"
            - "AUTHORS.rst"
            - "CHANGELOG.rst"
            - "CONTRIBUTING.rst"
            - "LICENSE"
            - "README.rst"
    pull_request:
        paths:
            - "docs/**"
            - "AUTHORS.rst"
            - "CHANGELOG.rst"
            - "CONTRIBUTING.rst"
            - "LICENSE"
            - "README.rst"

jobs:
    build:
        # We want to run on external PRs, but not on our own internal PRs as they'll be run
        # by the push to the branch. Without this if check, checks are duplicated since
        # internal PRs match both the push and pull_request events.
        if:
          github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
          github.repository
    
        runs-on: ubuntu-latest
        
        defaults:
          run:
            shell: bash -l {0}

        steps:
          - uses: actions/checkout@v2
          - uses: conda-incubator/setup-miniconda@v2
            with:
              miniforge-variant: Mambaforge
              miniforge-version: latest
              python-version: 3.8

          - name: Show conda installation info
            run: |
              mamba info
              mamba list
    
          - name: Install dependencies
            run: |
              mamba install --file=requirements.txt --file=requirements-docs.txt gimli.units
              pip install -e .

          - name: Build documentation
            run: make docs
