name: Test

on: [push, pull_request]

jobs:
  build-and-test:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Miniforge3
          miniforge-version: latest

      - name: Show conda installation info
        run: |
          conda info
          conda list

      - name: Install requirements
        run: |
          pip install -r requirements.txt -r requirements-testing.txt

      # - name: Install Windows requirements
      #   if: matrix.os == 'windows-latest'
      #   run: |
      #     conda install pymt_child pymt_hydrotrend pymt_permamodel

      # - name: Install Unix requirements
      #   if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      #   run: |
      #     conda install pymt_cem pymt_child pymt_hydrotrend pymt_permamodel

      - name: Build and install package
        run: |
          pip install -e .

      - name: Test
        run: |
          python -c 'import pymt; print(pymt.__version__)'
          pytest --cov=pymt --cov-report=xml:$(pwd)/coverage.xml -vvv

      - name: Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
        uses: AndreMiras/coveralls-python-action@v20201129
