name: Notebooks

on: [push, pull_request]

jobs:
  build-and-test:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}

      - name: Show conda installation info
        run: |
          mamba info
          mamba list

      - name: Install requirements
        run: |
          mamba install --file=requirements.txt
          mamba list

      - name: Build and install package
        run: |
          pip install -e .

      - name: Install testing dependencies
        run: |
          mamba install --file=requirements-testing.txt
          mamba install --file=requirements-notebooks.txt

      - name: Test jupyter notebooks
        timeout-minutes: 30
        run: |
          python -c 'import pymt; print(pymt.__version__)'
          pytest notebooks --run-notebook -vvv
