name: Test

on: [push, pull_request]

jobs:
  build-and-test:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}

      - name: Show conda installation info
        run: |
          mamba info
          mamba list

      - name: Install requirements
        run: |
          mamba install --file=requirements.txt --file=requirements-testing.txt
          mamba install gimli.units
          mamba list

      - name: Install Windows requirements
        if: matrix.os == 'windows-latest'
        run: |
          mamba install pymt_child pymt_hydrotrend pymt_permamodel

      - name: Install Unix requirements
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          mamba install esmpy
          mamba install pymt_cem pymt_child pymt_hydrotrend pymt_permamodel

      - name: Build and install package
        run: |
          pip install -e .

      - name: Install testing dependencies
        run: mamba install --file=requirements-testing.txt

      - name: Test
        run: |
          python -c 'import pymt; print(pymt.__version__)'
          pytest --cov=pymt --cov-report=xml:$(pwd)/coverage.xml -vvv

      - name: Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'
        uses: AndreMiras/coveralls-python-action@v20201129
