name: Notebooks

on: [push, pull_request]

jobs:
  build-and-test:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge
          channel-priority: true

      - name: Show conda installation info
        run: |
          mamba info
          mamba list

      - name: Install requirements
        run: |
          mamba install --file=requirements.txt
          mamba install gimli.units
          mamba list

      - name: Build and install package
        run: |
          pip install -e .

      - name: Install testing dependencies
        run: |
          mamba install --file=requirements-testing.txt
          mamba install --file=requirements-notebooks.txt

      - name: Test jupyter notebooks
        run: |
          python -c 'import pymt; print(pymt.__version__)'
          pytest notebooks --run-notebook -vvv
